agent:
  image: ictu/dashboard-agent:4.3
  environment:
    - USER=core
    - AUTH_TOKEN={{authToken}}
    - DOCKER_HOST=unix:///swarm/swarm.sock
    - TARGET_NIC={{targetNIC}}
    - TARGET_VLAN={{vlan}}
    - HTTP_PORT=80
    - ETCD_BASEURL=http://${etcdIP}:4001
    - BASE_DIR=/mnt/data/scripts
    - DATA_DIR=/mnt/data
    - SCRIPT_BASE_DIR=/mnt/data/scripts
    - SHARED_DATA_DIR=/mnt/data
    - ROOT_URL={{rootURL}}
    - SYSLOG_URL={{syslogURL}}
    - DOMAIN={{project}}
    - REMOTEFS_URL={{remotefsUrl}}
  volumes:
    - /local/data
    - /mnt/data
    - /var/run/docker.sock:/var/run/docker.sock
